public class Coincidencias{

	String criptotexto;
	String alfabeto = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

	public Coincidencias(){
		criptotexto = "WBTIARTYKNUMQOIULNXTIBSTUBHXPOOUEDYEEVQEEOZQHJHDULRUFKDBXIAOMBXATQICV";
		criptotexto += "SLOIEUFHICNTCDNBVFRTGHCHYORDKCNBACWOYAYCGLNIGVXPBIQRKMDCVIGDKPONIYVVUFUNZHGUF";
		criptotexto += "EIBDXWHBJVSRHMXVUHXNDIBAEMIAFMGJRBLXVBRNJHXDSEPRHSSVVURGBQOQZKWPNDIZNIKCNMWMW";
		criptotexto += "WKCHJXRDBMSFRTFDBIEUGUHLBSIHZUHLNOUGZELANBYLNOETXDKSRGFSFROILXKYKXBLIESSWWOOM";
		criptotexto += "XFLYUOCSOHBIUBIGKNIXFNHXMBHUKRDVCNBGXASFVJRXEJRXWHJXRWNTLDOYPHYQYWHHIABCIANRF";
		criptotexto += "QPOXMUOAVVIVLXBGEWIXHRAHVGBDPLRDUPRJCWBBIYDBJYLWVPXLUEFBCYYNUHMRIJMCUAWDBSKXBN";
		criptotexto += "WWQXPACWMOCGIQZZSOCUYUZKLTHUFTALITCHXMAWUVEWLAYOWEXQTFDZEEPNWSSBHSQEQKDUKGQHHUTM";
		criptotexto += "TYYDWKCRXHLNZTRHZTSWWHUXRENMHRMMLCGBRRHCUQTWWCWIMNEMEEERFNRIONIMMYQMGUYNIMRSBAOLIWR";
		criptotexto += "HIJGWEPIKEBQLEDPQXRQUFGVZITYBYZXRUXXFFIVSKCNOEGURTHTSMSORXVDDKXHYULWRIYXEQFMLSIVUOBN";
		criptotexto += "RDKPDZQSVRLCMVBFWNHCIJRXWWRXLNJXPEWGSDSRIQQXPDYUIOPEHQGHYLNIKCNYMKASXIYIGVXJXPJPNIQMEIGR";
		criptotexto += "JYHRBGHQHYDAPUAHUMMUTIYDSYMUZTMYZBGDGBIVOEDRYWIONUYMUSLWAPKIBSTVPLVISGOIUGYEVRDNDDKYTQEHL";
		criptotexto += "NEYVBISMWRTADABWRSGXHZXGLAVMRAFXRQUFFNRUTNIYVXLYVCIMCYWXKRPBHNDHVHZTQDOOMYVQIVGKPRDKYXRTIV";
		criptotexto += "HQYAYIMXJRTXDOQUYRTULNTIKJEUYDSXWHAXIKOEENHKELRHRTHFEQHQEOMEFPNUMXFSIUXUMMUOIZZIXIBQXVUSKSOF";
		criptotexto += "THLBKEHABWHQUUDCELYYLUTXQFICCUTJGMQNGXPXFLYDGXPONXPDPETURWOTUWIVZIXTXPTPOREPDFGHUBIISNZUGNKHUD";
		criptotexto += "YDWCSFKXAHIVOGSJRTYQENIURXWSNTRRSKYHZEHQRINMWIBIPOCLNGWTUWTHDSIIQFWIVHESVNOIQQYFHFULDZELTNCUANR";
		criptotexto += "TJQNVCCEIRAJIXQYYANHIVXDOMNZELNSLXLSUEGQAEFUXWWNRUXRTYBQYITTUHBRPUJJVUTJQNUNBXWJGIIUWTPDETZXRISQ";
		criptotexto += "DKCHYQHBFQVIMRLIICKCNSKTJGWIRFBEBVBGLRHRDGEEOYUJVHDIUJFTSEDHVTHXRVNRIPNDXRRBWINGOMMESKXBUIUQNKRO";
		criptotexto += "TPNGHFUZXWSNXGKBUEOYEBWRHJWBBUAYYMIJFNZJAXRXHXPNOJYLOKPHNXPONHEKVZUVNDWPYUNMWIYUNFFWBOXIBCVEKFXC";
		criptotexto += "GVZIYDSLIOYQGIKOEEPBBCVNFTCTHUYZJVBNDQUOVQCGVDQEGWUWGIUBTYIWHXUXRHUIUOVYDYJUUKWXRUBWILXBJYLWENM";
		criptotexto += "ZIXWHCKMQNGXHRAOMMUZTQDFUXWWOFSOVDYZJCYVHPYYVMCEIQHUPWBGXVYVSCWBMFIUPUXMB";
	}

	public int[] frecuencias(){
		int[] res = new int[26];
		char c;
		int indice;
		for(int i=0; i<criptotexto.length();i++){
			c = criptotexto.charAt(i);
			indice = alfabeto.indexOf(c);
			res[indice] +=1;
		}

		return res;
	}

	public static void main(String[] args){
		Coincidencias coin = new Coincidencias();

		int[] frec = coin.frecuencias();

		for(int i=0;i<frec.length;i++){
			System.out.print(coin.alfabeto.charAt(i)+": "+frec[i]+" ");
		}

		float indCoin = 0;
		float n = coin.criptotexto.length();
		for(int i=0;i<frec.length;i++){
			indCoin += (frec[i]*(frec[i]-1))/(n*(n-1));
		}

		System.out.println("\n"+indCoin);
	}
}
